repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.8
    hooks:
      - id: ruff
        # Fixes structural and styling rules across the whole project
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        # No 'files:' filter here, so it checks setup.py and scripts/ too!

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        files: ^src/mypytools/|^scripts/
        args: [--strict]

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        args: [-x]
        language: system
        pass_filenames: false
        always_run: true