repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        files: ^src/mypytools/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.8
    hooks:
      - id: ruff
        files: ^src/mypytools/
      - id: ruff-format
        files: ^src/mypytools/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        files: ^src/mypytools/
        args: [--strict]
        additional_dependencies: []

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        args: [-x]
        language: system
        pass_filenames: false
        always_run: true